version: '3.8'

services:
  web:
    build: ./webinar_project
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - ./webinar_project:/app
    ports:
      - 8008:8000
    env_file:
      - ./webinar_project/.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./webinar_project/.env

volumes:
  postgres_data: